# Generated by Django 2.2.16 on 2020-09-15 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo_maquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.IntegerField(choices=[(0, 'equipo'), (1, 'herramienta')])),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'equipo_maquinarias',
                'db_table': 'equipo_maquinaria',
                'ordering': ['-nombre', '-tipo', '-fecha_registro'],
                'verbose_name': 'equipo_maquinaria',
            },
        ),
    ]
