# Generated by Django 2.2.16 on 2020-09-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'ausente'), (1, 'asistio')])),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
            options={
                'verbose_name_plural': 'asistencias',
                'db_table': 'asistencia',
                'ordering': ['-empleado', '-estado'],
                'verbose_name': 'asistencia',
            },
        ),
    ]
