# Generated by Django 2.2.16 on 2020-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
