# Generated by Django 2.2.16 on 2020-09-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'presentaciones',
                'db_table': 'presentacion',
                'ordering': ['-nombre'],
                'verbose_name': 'presentacion',
            },
        ),
    ]
