# Generated by Django 2.2.16 on 2020-09-15 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo_maquinaria', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asig_eq_maq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asig', models.DateField(default=datetime.datetime.now)),
                ('observacion', models.CharField(max_length=30)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado')),
                ('equipo_maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_maquinaria.equipo_maquinaria')),
            ],
            options={
                'verbose_name_plural': 'asig_equipos_maquinas',
                'verbose_name': 'asig_eq_maq',
                'db_table': 'asig_eq_maq',
            },
        ),
    ]
