# Generated by Django 2.2.16 on 2020-09-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('tipo_doc', models.IntegerField(choices=[(1, 'CEDULA'), (0, 'RUC')], default=1)),
                ('numero_doc', models.CharField(max_length=13, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
                'ordering': ['-nombres', '-numero_doc'],
                'verbose_name': 'cliente',
            },
        ),
    ]
