# Generated by Django 2.2.16 on 2020-09-15 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.IntegerField(choices=[(0, 'DEVUELTA'), (1, 'FINALIZADA')], default=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor')),
            ],
            options={
                'verbose_name_plural': 'compras',
                'db_table': 'compra',
                'ordering': ['-id', 'proveedor'],
                'verbose_name': 'compra',
            },
        ),
        migrations.CreateModel(
            name='detalle_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.insumo')),
            ],
            options={
                'verbose_name_plural': 'detalles_compras',
                'db_table': 'detalle_compra',
                'ordering': ['id', 'compra'],
                'verbose_name': 'detalle_compra',
            },
        ),
    ]
