# Generated by Django 2.2.16 on 2020-09-19 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Activo '), (1, 'Inactivo')], default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_civil',
            field=models.IntegerField(choices=[(0, 'Casad@'), (1, 'Solter@')], default=0),
        ),
    ]
