# Generated by Django 2.2.16 on 2020-09-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20200919_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
