# Generated by Django 2.2.16 on 2020-09-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=0)),
            ],
            options={
                'verbose_name_plural': 'periodos',
                'verbose_name': 'periodo',
                'db_table': 'periodo',
            },
        ),
    ]
